eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
server:
 port: 8888
spring:

  rabbitmq:
      password: guest
      port: 5672
      host: localhost
      username: guest

  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          username: 554343346@qq.com
#          password: duan123
          uri: https://github.com/duan847/microservice
          searchPaths: config-repo
      label: master
    bus:
       trace:
          enabled: true

management:
  security:
     enabled: false