spring:
  rabbitmq:
    password: guest
    port: 5672
    host: localhost
    username: guest
  application:
    name: config-client
server:
  port: 8881
management:
   security:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${url}